### ISSUE TITLE
No Settings

### ISSUE THREAD

**Issue by caltrop-3** [mate-desktop/mate-screensaver#137] opened 2017-08-29 15:23 UTC
#### Expected behaviour
ability to change screensaver settings

#### Actual behaviour
no settings

#### Steps to reproduce the behaviour
open screensettings

#### MATE general version
18.2

#### Package version
unknown

#### Linux Distribution
Mint

#### Link to downstream report of your Distribution
none

##### screen shot
![screensaver - no settings](https://user-images.githubusercontent.com/31071746/29829082-816574fa-8cac-11e7-8771-c67e2dc1ca2f.png)

**Comment by alexarnaud** [comment] 2017-08-29 16:02
Hello caltrop-3,

The screenshot you've made is about XScreenSaver from the XFCE project. 
I mean you have an issue with XScreenSaver, isn't it?

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by caltrop-3** [comment] 2017-08-30 17:57
And the mate-screensaver which has NO settings!
I killed the mate-screensaver and am using x-screensaver since it allows me to configure the screensavers.When the mate-screensaver is fixed I will go back to using it.

**Comment by alexarnaud** [comment] 2017-08-31 09:00
Le 30/08/2017 à 19:57, caltrop-3 a écrit :
> And the mate-screensaver which has NO settings!
> I killed the mate-screensaver and am using x-screensaver since it allows 
> me to configure the screensavers.When the mate-screensaver is fixed I 
> will go back to using it.

Sure. Could you be more precise on the steps to reproduce your issue?
For example "no settings" doesn't mean anything for me, do you mean the 
window of mate-screensaver is empty? Do you mean the settings are not 
editable?
What do you mean by "open screensettings"? screensettings is not a valid 
command line on my Debian.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by alexarnaud** [comment] 2017-10-12 08:32
@caltrop-3 ping ?

**Comment by alexarnaud** [comment] 2017-11-14 11:19
@raveit65 could it be possible to close this issue because there is no update since more than one month ?

Best regards.

**Comment by MikeOhShark** [comment] 2017-11-15 14:25
Perhaps the original post was not clear. I have the same issue.

I am using Linux Mint, version 18.1 MATE 64 bit with mate-screensaver 1.16.0

When selecting a screensaver, for example Sonar, the buttons on the Screensaver Preferences dialog are Help, Power Management, Preview, and Close. There is no Settings button. Thus there is no obvious way of configuring the screensaver's options.

The above worked in Linux Mint 13 MATE.

I believe the settings can be adjusted by switching to xscreensaver but that is not my preference.

Please don't close the issue too soon. I'd like to see a fix or workaround.

Thanks!

**Comment by MikeOhShark** [comment] 2017-11-15 14:40
Sorry, I commented before seeing https://github.com/mate-desktop/mate-screensaver/issues/5

It appears to be a duplicate of the same issue.

**Comment by flexiondotorg** [comment] 2017-11-15 17:22
Duplicate of #5

**Closed by flexiondotorg** 2017-11-15 17:22 UTC
