### ISSUE TITLE
mate-screensaver unlocks and hangs when an external display is added or removed

### ISSUE THREAD

**Issue by cdkoresko** [mate-desktop/mate-screensaver#143] opened 2017-11-28 03:57 UTC
#### Expected behaviour
Upon resume from a screen-locked suspended state, the screen is locked and a password prompt is displayed regardless of whether a new display has been attached or removed when the computer was suspended.

#### Actual behaviour
Upon resume from a screen-locked suspended state, if a display has been attached or removed when the computer was suspended, then the screen is unlocked and cannot be locked either via a hotkey or a mate-screensaver command at a terminal.  Killing and restarting the mate-screensaver process gets it going again.

NB: I see this with a Quad-HD LCD connected to my Dell Latitude E6220 laptop via a DisplayPort cable attached to its dock.  Suspend the laptop with the screen locked, dock it, and resume it, and the unlocked desktop is displayed.  Same problem if the screen is locked and the laptop is suspended with the external display attached, and then the laptop is resumed after disconnecting the external display.

NB2: I haven't tested what happens when an external screen is connected or disconnected with the screen locked and the laptop running.

#### Steps to reproduce the behaviour
1) Lock the screen without an external display attached.
2) Suspend to RAM.
3) Connect an external display.
4) Resume from suspend.
5) Observe that the screen is no longer locked.
6) Attempt to lock the screen and observe that it fails.
7) (Optional): Kill the mate-screensaver process and restart it.  The screensaver will now operate normally until a display is added or removed.

#### MATE general version
mate-desktop-1.19.1-1.fc27.x86_64

#### Package version
1.19

#### Linux Distribution
Fedora 27 (this bug was seen previously with Fedora 26 and with Arch Linux).

#### Link to downstream report of your Distribution

**### NB: The issue I describe above appears to be identical to the one in https://github.com/mate-desktop/mate-screensaver/issues/126#issuecomment-319489655**

**Comment by mannih** [comment] 2017-12-04 10:35
AFAIK, steps 2 and 4 aren't necessary to trigger the bug.

**Comment by joakim-tjernlund** [comment] 2017-12-27 00:46
Yes, this looks very similar to #126 
Seems hard to root cause so adding more debug info to this ticket would help.

**Comment by cdkoresko** [comment] 2017-12-27 00:57
Would capturing the output of running 'mate-screensaver  --debug' while provoking the bug to manifest be useful?

**Comment by joakim-tjernlund** [comment] 2018-01-04 04:07
I am getting somewhat desperate, this bug and similar are driving people at work into KDE
and I don't like that as they also want me to support them. It really needs to
be fixed.

I had a look in gtk and found signals "monitor-added"/"monitor-removed". There is
no code dealing with these signals, maybe there need to be?

**Comment by cdkoresko** [comment] 2018-01-05 01:45
I tried uninstalling mate-screensaver and installing light-locker.  I haven't tested it thoroughly yet, but so far it looks good.  This is with Fedora 27.

**Comment by raveit65** [comment] 2018-02-02 11:54
i can't fix it, ask someone other of the team.

**Comment by joakim-tjernlund** [comment] 2018-02-02 12:02
Who? This ( and #126 ) has been known for a while to several devs but no one has accepted to
fix it.

**Comment by rathann** [comment] 2018-03-22 08:09
Shouldn't this be closed as duplicate of #126 ?

**Comment by cdkoresko** [comment] 2018-03-22 13:52
Yes, they are describing the same behavior as far as I can tell.
	Chris

**Comment by raveit65** [comment] 2018-09-08 22:03
1.20.2 is released.

**Closed by raveit65** 2018-09-08 22:03 UTC
