### ISSUE TITLE
deprecated gtk3 warnings for mate-power-preferences 

### ISSUE THREAD

**Issue by shirishag75** [mate-desktop/mate-screensaver#95] opened 2016-05-30 20:06 UTC
Hi all, 
I am on Debian unstable. Whenever I run mate-power-preferences on unstable/sid I get the following -

```
[$] mate-screensaver-preferences                                                                                                    

(mate-screensaver-preferences:23303): Gtk-WARNING **: Theme parsing error: gtk.css:63:28: The :prelight pseudo-class is deprecated. Use :hover instead.

(mate-screensaver-preferences:23303): Gtk-WARNING **: Theme parsing error: gtk.css:73:35: The :prelight pseudo-class is deprecated. Use :hover instead.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(/usr/lib/mate-screensaver/mate-screensaver-gl-helper:23306): Gtk-WARNING **: Theme parsing error: gtk.css:63:28: The :prelight pseudo-class is deprecated. Use :hover instead.

(/usr/lib/mate-screensaver/mate-screensaver-gl-helper:23306): Gtk-WARNING **: Theme parsing error: gtk.css:73:35: The :prelight pseudo-class is deprecated. Use :hover instead.

(mate-screensaver-preferences:23303): GLib-GObject-WARNING **: /build/glib2.0-wnDt2X/glib2.0-2.48.1/./gobject/gsignal.c:2517: signal 'size-request' is invalid for instance '0x5628f51ac2b0' of type 'GtkScrolledWindow'
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(mate-power-preferences:23345): Gtk-WARNING **: Theme parsing error: gtk.css:63:28: The :prelight pseudo-class is deprecated. Use :hover instead.

(mate-power-preferences:23345): Gtk-WARNING **: Theme parsing error: gtk.css:73:35: The :prelight pseudo-class is deprecated. Use :hover instead.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

```

Could somebody fix the gtk3 deprecated warnings and the GTK-messages . Please let me know if you need any more info.

**Comment by raveit65** [comment] 2016-05-30 21:26
As you can read this are warnings about a theme which isn't ported to gtk+-3.20.
Complete unrelated to m-s, you will see that warnings with any other app in terminal.
Which gtk theme are you using?

**Comment by shirishag75** [comment] 2016-05-31 00:51
I am using menta which is part of mate-themes and from what I can see and observe it seems to have a gtk3 port as well as gtk2. Maybe some part of the theme is still gtk2.0, dunno about that,  

```
$ aptitude show mate-themes | grep Version                                                                                        
Version: 3.20.7-1
```

```
[/usr/share/themes/Menta] - [10100]
└─[$] ls
                                                                                                                             
cinnamon  emerald  gtk-2.0  gtk-3.0  index.theme  metacity-1  README  unity  xfwm4

```
The only way I know what the theme is by right-clicking on the mate-desktop > clicking on Change Desktop Background > Theme > Menta . The only modification I have done to the theme is used a black pointer instead of the white pointer which comes by default. Have no idea which theme does the black pointer belong to though.

**Comment by raveit65** [comment] 2016-05-31 07:13
I'm really in doubt that your post is from Menta theme, because taken from your post 
```
(mate-screensaver-preferences:23303): Gtk-WARNING **: Theme parsing error: gtk.css:63:28: The :prelight pseudo-class is deprecated. Use :hover instead.
```
Menta theme does not have those entries :smile: 
https://github.com/mate-desktop/mate-themes/blob/gtk3.22/desktop-themes/Menta/gtk-3.0/gtk.css

And i do not see this deprecated warnings with any Mate theme.
[rave@mother ~]$ gsettings get org.mate.interface gtk-theme
'Menta'

**Comment by raveit65** [comment] 2016-05-31 07:36
Btw. you're first post is about mate-screensaver-preferences and not mate-power-preferences :smile:

**Comment by shirishag75** [comment] 2016-05-31 07:51
At my end - 
```
[$] gsettings get org.mate.interface gtk-theme
                                                                                     
'Menta'

```

For both I get similar messages - 

```
─[$] mate-screensaver-preferences                                                                                                   

(mate-screensaver-preferences:5645): Gtk-WARNING **: Theme parsing error: gtk.css:63:28: The :prelight pseudo-class is deprecated. Use :hover instead.

(mate-screensaver-preferences:5645): Gtk-WARNING **: Theme parsing error: gtk.css:73:35: The :prelight pseudo-class is deprecated. Use :hover instead.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(/usr/lib/mate-screensaver/mate-screensaver-gl-helper:5648): Gtk-WARNING **: Theme parsing error: gtk.css:63:28: The :prelight pseudo-class is deprecated. Use :hover instead.

(/usr/lib/mate-screensaver/mate-screensaver-gl-helper:5648): Gtk-WARNING **: Theme parsing error: gtk.css:73:35: The :prelight pseudo-class is deprecated. Use :hover instead.

(mate-screensaver-preferences:5645): GLib-GObject-WARNING **: /build/glib2.0-wnDt2X/glib2.0-2.48.1/./gobject/gsignal.c:2517: signal 'size-request' is invalid for instance '0x563ed25c62b0' of type 'GtkScrolledWindow'


```

And this is mate-screensaver-preferences 

```
[$] mate-screensaver-preferences                                                                                                   

(mate-screensaver-preferences:5707): Gtk-WARNING **: Theme parsing error: gtk.css:63:28: The :prelight pseudo-class is deprecated. Use :hover instead.

(mate-screensaver-preferences:5707): Gtk-WARNING **: Theme parsing error: gtk.css:73:35: The :prelight pseudo-class is deprecated. Use :hover instead.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(/usr/lib/mate-screensaver/mate-screensaver-gl-helper:5710): Gtk-WARNING **: Theme parsing error: gtk.css:63:28: The :prelight pseudo-class is deprecated. Use :hover instead.

(/usr/lib/mate-screensaver/mate-screensaver-gl-helper:5710): Gtk-WARNING **: Theme parsing error: gtk.css:73:35: The :prelight pseudo-class is deprecated. Use :hover instead.

(mate-screensaver-preferences:5707): GLib-GObject-WARNING **: /build/glib2.0-wnDt2X/glib2.0-2.48.1/./gobject/gsignal.c:2517: signal 'size-request' is invalid for instance '0x56296a9082b0' of type 'GtkScrolledWindow'

```

Both are the latest from Debian sid/unstable.

**Comment by raveit65** [comment] 2016-05-31 08:00
You did not understand my hint, again.
Menta theme does not have those entries.
https://github.com/mate-desktop/mate-themes/blob/gtk3.22/desktop-themes/Menta/gtk-3.0/gtk.css
Do you have themes in ~.themes ?

**Comment by shirishag75** [comment] 2016-05-31 08:31
I do have .themes sub-directory but it's empty. 

```
┌─[shirish@debian] - [~/.themes] - [10019]
└─[$] ls                                                                                                                      
┌─[shirish@debian] - [~/.themes] - [10020]
```

**Comment by raveit65** [comment] 2016-05-31 08:42
Can you give me this output?
```
[root@mother rave]# cat /usr/share/themes/Menta/gtk-3.0/gtk.css 
@import url("gtk-main.css");
```
As you can see there are no entries which are mentioned in your post.
@sunweaver
can you reproduce this?

**Comment by shirishag75** [comment] 2016-05-31 09:13
I get the following when trying it on bash or zsh

```
root@debian:/home/shirish# cat /usr/share/themes/Menta/gtk-3.0/gtk.css 
@import url("gtk-main.css");

root@debian:/home/shirish# @import url("gtk-main.css");

```
Dunno what it means.

**Comment by raveit65** [comment] 2016-05-31 10:14
Ok, this means it is impossible that those warning are from Menta themes.
Sorry, i don't have debian installed, someone from debian guys here should try to reproduce this.

**Comment by monsta** [comment] 2016-05-31 12:45
I don't see these warnings with 1.14 (GTK+3 build) and ```mate-themes``` from 3.20 branch (both latest commit and 3.20.7 tag). This VM has Debian Testing though, not Unstable. Might be something in Debian packaging in Unstable...

**Comment by shirishag75** [comment] 2016-05-31 21:34
@monsta and @raveit65  I dug and it seems it's a GNOME 3 theme which I have got which is causing the issue. 

```
[~/.config/gtk-3.0] 
└─[$] cat settings.ini                                                                                                                
[Settings]
gtk-theme-name=AlaDelta
gtk-icon-theme-name=matefaenzagray
gtk-font-name=Sans 12
gtk-cursor-theme-name=DMZ-Black
gtk-cursor-theme-size=48
gtk-toolbar-style=GTK_TOOLBAR_BOTH_HORIZ
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=1
gtk-menu-images=1
gtk-enable-event-sounds=0
gtk-enable-input-feedback-sounds=0
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintmedium
gtk-xft-rgba=none
gtk-application-prefer-dark-theme=1

```
Now it either is gtk-theme-name=AlaDelta or gtk-cursor-theme-name=DMZ-Black which is at fault. I tried to remove/delete settings.ini but even after delete/removing settings.ini it comes back. It means, the value is set somewhere else and it's being fed by a gtk theme about which I have nothing/ no knowledge about. Can somebody help to track that.

**Comment by raveit65** [comment] 2016-05-31 22:14
I dunno, i never used a .config/gtk-3.0 for myself
I suggest simply uninstall/delete the theme.
AlaDelta is a fork from adwaita and it is obsolete since several years.
I'm in doubt that someone will ever port this theme to  3.20, a complete rewrite is needed ;)
Maybe 400 hours or so.........
I hope you agree with me to close this issue as it is not related to MATE.

**Closed by raveit65** 2016-05-31 22:14 UTC
