### ISSUE TITLE
idle slider display bug 

### ISSUE THREAD

**Issue by apolitech** [mate-desktop/mate-screensaver#101] opened 2016-09-15 09:27 UTC
The display timer is over the slider button (see pic's) 
This is the normal way 
![2](https://cloud.githubusercontent.com/assets/14872517/18544923/a5980e0c-7b3f-11e6-8c26-d231a1fdccc0.png)

And this is with the bug
![1](https://cloud.githubusercontent.com/assets/14872517/18544942/b54ce278-7b3f-11e6-86d5-723d75066a14.png)

Tested on Ubuntu MATE 16.10 daily with MATE 1.15 latest 
Reported to Ubuntu MATE launchpad https://bugs.launchpad.net/ubuntu-mate/+bug/1623196
##

**Comment by jmlich** [comment] 2016-12-02 13:40
I have noticed this behaviour also on fedora 25. See https://bugzilla.redhat.com/show_bug.cgi?id=1400554
Additionally, I would prefer use of spinbox widget instead of slider.

**Comment by raveit65** [comment] 2016-12-27 19:55
I updated glade file for preferences yesterday but i found only one option to control the text.
Moving it to right, left or bottom of the GtkScale makes it not better.
I guess problem code is here.
 https://github.com/mate-desktop/mate-screensaver/blob/master/src/mate-screensaver-preferences.c#L927

**Comment by monsta** [comment] 2017-03-28 12:32
For some reason I can't reproduce it with GTK+ 3.14 (using MATE 1.18).

**Comment by monsta** [comment] 2017-03-28 12:33
With 3.20 and 3.22 this is of course reproducible. I'll check 3.18 as well when I'll get home today.

**Comment by monsta** [comment] 2017-03-28 18:06
Ok, not reproducible with 3.18. So... maybe just another CSS-related breakage in GTK+ >= 3.20?

**Comment by raveit65** [comment] 2017-03-28 18:49
There was a big change for GtkScale with 3.20/22.
Not only css related.

**Closed** 2017-09-08 19:34 UTC
Labels: confirmed
